export class MyCommunityModel {
    public id?: string;
    public email?: string;
    public username?: string;
    public nickname?: string | null;
    public contract_id?: string | null;
    public externalWalletId?: string;
    public account_type?: string;
    public documentToken?: string;
    public externalId?: string | null;
    public tron_wallet?: string | null;
    public btc_wallet?: string;
    public vault_id?: string | null;
    public phone?: string;
    public selfieImage?: string | null;
    public firstName?: string;
    public name?: string | null;
    public wasPaid?: boolean | null;
    public should_wait_contract?: boolean | null;
    public lastName?: string;
    public clientSecret?: string | null;
    public receivesNewletter?: boolean | null;
    public clientId?: string | null;
    public when?: Date;
    public cpf?: string;
    public discord_id?: string | null;
    public invitedBy?: string;
    public kycReportId?: string;
    public acceptedInvite?: Date;
    public challengeLoginFlowDate?: Date | null;
    public status?: string | null;
    public indicationRewardStatus?: string | null;
    public statusUpdatedAt?: Date | null;
    public externalSourceIndication?: string | null;
    public externalSourceId?: string;
    public mfaStatus?: string | null;
    public sentBrlaLvlOne?: boolean | null;
    public sentBrlaLvlTwo?: boolean | null;
    public dateOfBirth?: Date;
    public openingDate?: Date | null;
    public identityCompanyManager?: string | null;
    public isPhoneVerified?: boolean;
    public level?: number;
}