export enum PaymentTypesEnum {
    PIX = "PIX",
    CIELO = "CIELO",
    MULTICURRENCY = "MULTICURRENCY",
    COIN_PAYMENTS = "COIN_PAYMENTS",
    DEPOSITS = "DEPOSITS",
    PAGSEGURO = "PAGSEGURO",
    BRLA = "BRLAUSDT",
    CELCOIN_INTEGRATION = 'CELCOIN_INTEGRATION',
    NETELLER = "NETELLER",
    DIGITAL_BANKING = "DIGITAL_BANKING",
    CLEAR_LEDGER = "CLEAR_LEDGER",
    BRASIL_CASH = "BRASIL_CASH",
    TRANSFERA = "TRANSFERA",
    TRANSAK = "TRANSAK"
}