export const environment = {
    apiBaseUrl: 'API_BASE_URL',
    pageTitle: 'Tokeniza',
    isCapacitor:false,
    mockExchange: false,
    tokenIdWall: 'a',
    projectName: 'Tokeniza',
    firstRoute: '/tokenization/crowdfunding',
    graphUrl: 'a',
    showGraph: false,
    pixelId: '',
    BankingCheckout: false,
    collectionId: 'e40b9792-0b78-4a1a-b2a5-45c61e659667',
    baseUrl: 'tokeniza.com.br',
    oneSignalId: '',
    showAccountImage: false,
    tokenExchange: 'BTC',
    isKrakenIntegrationEnabled: false,
    signupExternal: false,
    signupURL: '',
    WS_ENDPOINT: "a",
    decimalPlaces: '1.6-6',
    decimalsPlacesBought: 6,
    mainRoute: '/tokenization/crowdfunding',
    showHeaderBuy: false,
    billNameCompany:"Tokeniza",
    companyName: 'Tokeniza',
    cnpj: '',
    waterMark: false,
    webService: 'ws://54.144.94.179:5000',
    priority: 'light'
};