export const environment = {
    apiBaseUrl: '/api',
    contactUsPhone: '+55 (61) 99874-3199',
    email: 'contato@tokeniza.com.br',
    contactUsEmail: 'https://tokeniza.com.br/fale-conosco/',
    pageTitle: 'Tokeniza',
    projectName: 'Tokeniza',
    companyName: 'Tokeniza',
    firstRoute: '/crowdfunding',
    pixelId: '',
    tokenIdWall: '',
    tokenDidit: 'cc27010d-b708-4cf9-b201-9c186d33833f',
    decimalsPlacesBought: 3,
    decimalPlaces: '1.6-6',
    baseUrl: 'axiadigitalsolutions.net', //TODO change
    teachingMaterialUrl: 'https://axia-tokeniza-us-east-2-s3-bucket.s3.us-east-2.amazonaws.com/MATERIAL_DIDATICO_DO_INVESTIDOR_-_12.08.2025.pdf',
    codeConductUrl: 'https://tokeniza.com.br/codigo-de-conduta-da-tokeniza/',
    crowdfundingRegulationUrl: 'https://conteudo.cvm.gov.br/legislacao/resolucoes/resol088.html',
    privacyPolicyUrl: 'https://tokeniza.com.br/aviso-de-privacidade/',
    cvmAuthorizationUrl: 'https://www.in.gov.br/en/web/dou/-/ato-declaratorio-cvm-n-20.906-de-29-de-maio-de-2023-486556692',
    termsUrl: 'https://tokeniza.com.br/termos-e-condicoes-de-uso/',
    faqUrl: 'https://tokeniza.com.br/faq/',
    blogUrl: 'https://tokeniza.com.br/blog/',
    contactUsUrl: 'https://tokeniza.com.br/fale-conosco',
    whoWeAreUrl: 'https://tokeniza.com.br/quem-somos/',
    youtubeUrl: 'https://www.youtube.com/playlist?list=PLTQZxU7migqpjbzp9CQRaKWlc4Pg5lP0A',
    wantCaptureUrl: 'https://tokeniza.com.br/captador/',
    instagramUrl: 'https://www.instagram.com/tokeniza.com.br/',
    linkedinUrl: 'https://www.linkedin.com/company/tokeniza-tknz/',
    isCapacitor: false
};