events{}
http {
    include /etc/nginx/mime.types;
    server {
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options nosniff;
        add_header Referrer-Policy "strict-origin";
        add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
        add_header X-XSS-Protection "1; mode=block";
        add_header Permissions-Policy "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(self),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()";
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 10M;
        listen 8080;
        server_name localhost;
        gzip            on;
        gzip_static     on;
        gzip_types      text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        gzip_proxied    no-cache no-store private expired auth;
        gzip_min_length 1000;
        root /axia;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
            index  index.html index.htm;
            client_max_body_size 10M;
        }

        location /api/ {
		    proxy_pass API_BASE_URL_NGNIX;
            client_max_body_size 10M;
		}
        proxy_connect_timeout   120;
        proxy_send_timeout      120;
        proxy_read_timeout      120;
        send_timeout            120;
        client_body_timeout     120;
    }
}
